// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const MOCKUP_CASKS: any = [
    {
        id: 1,
        name: "Dalrymple 2015",
        distillery: "Ex Bourbon Barrel",
        abv: "45.1%",
        currentValuation: "45,700",
        currency: "$",
        imageUrl: "/images/cask_mock.jpg",
    },
    {
        id: 2,
        name: "Dalrymple 2015",
        distillery: "Ex Bourbon Barrel",
        abv: "45.1%",
        currentValuation: "45,700",
        currency: "$",
        imageUrl: "/images/cask_mock.jpg",
    },
    {
        id: 3,
        name: "Dalrymple 2015",
        distillery: "Ex Bourbon Barrel",
        abv: "45.1%",
        currentValuation: "45,700",
        currency: "$",
        imageUrl: "/images/cask_mock.jpg",
    },
    {
        id: 4,
        name: "Dalrymple 2015",
        distillery: "Ex Bourbon Barrel",
        abv: "45.1%",
        currentValuation: "45,700",
        currency: "$",
        imageUrl: "/images/cask_mock.jpg",
    },
    {
        id: 5,
        name: "Dalrymple 2015",
        distillery: "Ex Bourbon Barrel",
        abv: "45.1%",
        currentValuation: "45,700",
        currency: "$",
        imageUrl: "/images/cask_mock.jpg",
    },
    {
        id: 6,
        name: "Dalrymple 2015",
        distillery: "Ex Bourbon Barrel",
        abv: "45.1%",
        currentValuation: "45,700",
        currency: "$",
        imageUrl: "/images/cask_mock.jpg",
    },
    {
        id: 7,
        name: "Dalrymple 2015",
        distillery: "Ex Bourbon Barrel",
        abv: "45.1%",
        currentValuation: "45,700",
        currency: "$",
        imageUrl: "/images/cask_mock.jpg",
    },
];
